"""Shared canonical book substrate and cross-mechanism runtime contracts."""

from .book_document import BookChapter, BookDocument, BookMetadata, ChapterHeadingBlock, ParagraphRecord, SentenceRecord, TextLocator, TextRole
from .normalized_outputs import (
    AttentionEventKind,
    CurrentReadingPhase,
    NormalizedAttentionEvent,
    NormalizedChapterOutput,
    NormalizedEvalBundle,
    NormalizedReaction,
    NormalizedRunSnapshot,
    ReactionType,
    SearchHit,
    ThoughtFamily,
)
from .runtime_contracts import (
    CheckpointSummary,
    CurrentReadingProblemCode,
    JobKind,
    JobRecord,
    JobStatus,
    MarkType,
    MechanismInfo,
    ParseRequest,
    ParseResult,
    ResumeKind,
    ReadRequest,
    ReadResult,
    ReadTaskMode,
    RuntimeArtifactRefs,
    RuntimeCursorKind,
    RuntimeShellState,
    SharedRunCursor,
    UserMark,
    UserMarksState,
    stable_config_fingerprint,
)
from .sentences import build_sentence_records, ensure_book_document_sentence_layer, split_text_into_sentence_spans, split_text_into_sentences
from .storage import book_document_file, existing_book_document_file, load_book_document, save_book_document

__all__ = [
    "AttentionEventKind",
    "BookChapter",
    "BookDocument",
    "BookMetadata",
    "CheckpointSummary",
    "ChapterHeadingBlock",
    "CurrentReadingPhase",
    "CurrentReadingProblemCode",
    "JobKind",
    "JobRecord",
    "JobStatus",
    "MarkType",
    "MechanismInfo",
    "NormalizedAttentionEvent",
    "NormalizedChapterOutput",
    "NormalizedEvalBundle",
    "NormalizedReaction",
    "NormalizedRunSnapshot",
    "ParagraphRecord",
    "SentenceRecord",
    "ParseRequest",
    "ParseResult",
    "ReactionType",
    "ReadRequest",
    "ReadResult",
    "ReadTaskMode",
    "ResumeKind",
    "RuntimeArtifactRefs",
    "RuntimeCursorKind",
    "RuntimeShellState",
    "SearchHit",
    "SharedRunCursor",
    "TextLocator",
    "TextRole",
    "ThoughtFamily",
    "UserMark",
    "UserMarksState",
    "build_sentence_records",
    "book_document_file",
    "ensure_book_document_sentence_layer",
    "existing_book_document_file",
    "load_book_document",
    "save_book_document",
    "split_text_into_sentence_spans",
    "split_text_into_sentences",
    "stable_config_fingerprint",
]
