"""Prompt registry package for attentional_v2."""

from .assembly import (
    PromptFragment,
    PromptFragmentRegistry,
    PromptTemplateNode,
    render_prompt_template_xml,
    render_digest_xml_prompt_example,
)
from .assembler import (
    PromptAssembler,
    PromptAssemblyResult,
    PromptAssemblySpec,
)
from .registry import (
    ATTENTIONAL_V2_PROMPTS,
    ATTENTIONAL_V2_PROMPTSET_VERSION,
    ATTENTIONAL_V2_PROMPT_REGISTRY,
    BRIDGE_RESOLUTION_PROMPT_VERSION,
    CHAPTER_CONSOLIDATION_PROMPT_VERSION,
    INGEST_PROMPT_VERSION,
    DIGEST_PROMPT_VERSION,
    RECONSOLIDATION_PROMPT_VERSION,
    REFLECTIVE_PROMOTION_PROMPT_VERSION,
    SURVEY_CHAPTER_ZONE_PROMPT_VERSION,
    AttentionalV2PromptSet,
    PromptDefinition,
    PromptRegistry,
)
from .reader_role import READER_ROLE_FRAGMENT, READER_ROLE_FRAGMENT_REGISTRY
from .ingest import (
    INGEST_BOOK_INFO_TEMPLATE,
    INGEST_OUTPUT_CONTRACT_TEMPLATE,
    INGEST_PROMPT_FRAGMENT_REGISTRY,
    INGEST_READER_ROLE_AND_INSTRUCTION_TEMPLATE,
    INGEST_RETRIEVAL_SURFACE_TEMPLATE,
    INGEST_TRANSPORT_SYSTEM_PROMPT,
    INGEST_XML_PROMPT_ASSEMBLY_SPEC_ID,
    INGEST_XML_PROMPTSET_VERSION,
    build_ingest_prompt_assembly_spec,
    render_ingest_prompt_xml,
)
from .digest import (
    DIGEST_BOOK_INFO_TEMPLATE,
    DIGEST_CURRENT_FOCUS_TEMPLATE,
    DIGEST_OUTPUT_CONTRACT_FRAGMENT_REGISTRY,
    DIGEST_OUTPUT_CONTRACT_TEMPLATE,
    DIGEST_READING_STATE_TEMPLATE,
    DIGEST_READER_ROLE_AND_INSTRUCTION_FRAGMENT_REGISTRY,
    DIGEST_READER_ROLE_AND_INSTRUCTION_TEMPLATE,
    DIGEST_ROLE_AND_INSTRUCTION_FRAGMENTS,
    DIGEST_XML_PROMPT_ASSEMBLY_SPEC_ID,
    DIGEST_XML_PROMPTSET_VERSION,
    DIGEST_XML_TRANSPORT_SYSTEM_PROMPT,
    build_digest_prompt_assembly_spec,
    render_digest_book_info_xml,
    render_digest_current_focus_xml,
    render_digest_output_contract_xml,
    render_digest_prompt_xml,
    render_digest_reading_state_xml,
    render_digest_reader_role_and_instruction_xml,
)


__all__ = [
    "ATTENTIONAL_V2_PROMPTS",
    "ATTENTIONAL_V2_PROMPTSET_VERSION",
    "ATTENTIONAL_V2_PROMPT_REGISTRY",
    "SURVEY_CHAPTER_ZONE_PROMPT_VERSION",
    "INGEST_PROMPT_VERSION",
    "DIGEST_PROMPT_VERSION",
    "READER_ROLE_FRAGMENT",
    "READER_ROLE_FRAGMENT_REGISTRY",
    "DIGEST_READER_ROLE_AND_INSTRUCTION_FRAGMENT_REGISTRY",
    "DIGEST_READER_ROLE_AND_INSTRUCTION_TEMPLATE",
    "DIGEST_BOOK_INFO_TEMPLATE",
    "DIGEST_CURRENT_FOCUS_TEMPLATE",
    "DIGEST_READING_STATE_TEMPLATE",
    "DIGEST_OUTPUT_CONTRACT_FRAGMENT_REGISTRY",
    "DIGEST_OUTPUT_CONTRACT_TEMPLATE",
    "DIGEST_ROLE_AND_INSTRUCTION_FRAGMENTS",
    "DIGEST_XML_PROMPT_ASSEMBLY_SPEC_ID",
    "DIGEST_XML_PROMPTSET_VERSION",
    "DIGEST_XML_TRANSPORT_SYSTEM_PROMPT",
    "INGEST_PROMPT_FRAGMENT_REGISTRY",
    "INGEST_READER_ROLE_AND_INSTRUCTION_TEMPLATE",
    "INGEST_BOOK_INFO_TEMPLATE",
    "INGEST_RETRIEVAL_SURFACE_TEMPLATE",
    "INGEST_OUTPUT_CONTRACT_TEMPLATE",
    "INGEST_XML_PROMPT_ASSEMBLY_SPEC_ID",
    "INGEST_XML_PROMPTSET_VERSION",
    "INGEST_TRANSPORT_SYSTEM_PROMPT",
    "build_ingest_prompt_assembly_spec",
    "render_ingest_prompt_xml",
    "build_digest_prompt_assembly_spec",
    "render_digest_prompt_xml",
    "render_digest_reader_role_and_instruction_xml",
    "render_digest_book_info_xml",
    "render_digest_current_focus_xml",
    "render_digest_reading_state_xml",
    "render_digest_output_contract_xml",
    "BRIDGE_RESOLUTION_PROMPT_VERSION",
    "REFLECTIVE_PROMOTION_PROMPT_VERSION",
    "RECONSOLIDATION_PROMPT_VERSION",
    "CHAPTER_CONSOLIDATION_PROMPT_VERSION",
    "AttentionalV2PromptSet",
    "PromptDefinition",
    "PromptRegistry",
    "PromptFragment",
    "PromptFragmentRegistry",
    "PromptTemplateNode",
    "PromptAssembler",
    "PromptAssemblyResult",
    "PromptAssemblySpec",
    "render_prompt_template_xml",
    "render_digest_xml_prompt_example",
]
