"""Phase 1 scaffold for the attentional_v2 reading mechanism."""

from .schemas import (
    ATTENTIONAL_V2_MECHANISM_VERSION,
    ATTENTIONAL_V2_POLICY_VERSION,
    ATTENTIONAL_V2_SCHEMA_VERSION,
    build_default_reader_policy,
    build_empty_anchor_memory,
    build_empty_local_buffer,
    build_empty_knowledge_activations,
    build_empty_move_history,
    build_empty_reconsolidation_records,
    build_empty_reflective_summaries,
    build_empty_trigger_state,
    build_empty_working_pressure,
)
from .state_ops import (
    append_anchor_relation,
    append_move,
    append_reconsolidation_record,
    close_local_meaning_unit,
    push_local_buffer_sentence,
    replace_policy_section,
    replace_pressure_bucket,
    set_gate_state,
    set_pressure_snapshot,
    set_trigger_result,
    upsert_anchor_record,
    upsert_knowledge_activation,
    upsert_reflective_item,
)
from .retrieval import bounded_lookback_source_space, flatten_sentence_inventory, generate_candidate_set
from .survey import build_book_survey, build_revisit_index, write_book_survey_artifacts
from .storage import ATTENTIONAL_V2_MECHANISM_KEY, artifact_map, initialize_artifact_tree

__all__ = [
    "ATTENTIONAL_V2_MECHANISM_KEY",
    "ATTENTIONAL_V2_MECHANISM_VERSION",
    "ATTENTIONAL_V2_POLICY_VERSION",
    "ATTENTIONAL_V2_SCHEMA_VERSION",
    "append_anchor_relation",
    "append_move",
    "append_reconsolidation_record",
    "close_local_meaning_unit",
    "artifact_map",
    "build_default_reader_policy",
    "build_book_survey",
    "build_revisit_index",
    "bounded_lookback_source_space",
    "build_empty_anchor_memory",
    "build_empty_local_buffer",
    "build_empty_knowledge_activations",
    "build_empty_move_history",
    "build_empty_reconsolidation_records",
    "build_empty_reflective_summaries",
    "build_empty_trigger_state",
    "build_empty_working_pressure",
    "flatten_sentence_inventory",
    "generate_candidate_set",
    "initialize_artifact_tree",
    "push_local_buffer_sentence",
    "replace_policy_section",
    "replace_pressure_bucket",
    "set_gate_state",
    "set_pressure_snapshot",
    "set_trigger_result",
    "upsert_anchor_record",
    "upsert_knowledge_activation",
    "upsert_reflective_item",
    "write_book_survey_artifacts",
]
