"""Scaffold and node toolkit for the in-progress attentional_v2 reading mechanism."""

from .bridge import (
    apply_bridge_state_updates,
    bridge_resolution,
    build_anchor_record,
    candidate_pool_for_bridge_resolution,
    derive_anchor_id,
    index_anchor_memory,
    run_phase5_bridge_cycle,
)
from .knowledge import (
    apply_activation_operations,
    live_activations,
    refresh_knowledge_modes,
    resolve_search_policy_mode,
    set_knowledge_use_mode,
    set_search_policy_mode,
)
from .nodes import controller_decision, meaning_unit_closure, reaction_emission, run_phase4_local_cycle, zoom_read
from .prompts import (
    ATTENTIONAL_V2_PROMPTS,
    ATTENTIONAL_V2_PROMPTSET_VERSION,
    BRIDGE_RESOLUTION_PROMPT_VERSION,
    CONTROLLER_DECISION_PROMPT_VERSION,
    MEANING_UNIT_CLOSURE_PROMPT_VERSION,
    REACTION_EMISSION_PROMPT_VERSION,
    ZOOM_READ_PROMPT_VERSION,
)
from .retrieval import bounded_lookback_source_space, flatten_sentence_inventory, generate_candidate_set
from .schemas import (
    ATTENTIONAL_V2_MECHANISM_VERSION,
    ATTENTIONAL_V2_POLICY_VERSION,
    ATTENTIONAL_V2_SCHEMA_VERSION,
    build_default_reader_policy,
    build_empty_anchor_memory,
    build_empty_local_buffer,
    build_empty_knowledge_activations,
    build_empty_move_history,
    build_empty_reconsolidation_records,
    build_empty_reflective_summaries,
    build_empty_trigger_state,
    build_empty_working_pressure,
)
from .state_ops import (
    append_anchor_relation,
    append_move,
    append_reconsolidation_record,
    apply_working_pressure_operations,
    close_local_meaning_unit,
    push_local_buffer_sentence,
    replace_policy_section,
    replace_pressure_bucket,
    set_gate_state,
    set_pressure_snapshot,
    set_trigger_result,
    upsert_anchor_record,
    upsert_knowledge_activation,
    upsert_reflective_item,
)
from .survey import build_book_survey, build_revisit_index, write_book_survey_artifacts
from .storage import ATTENTIONAL_V2_MECHANISM_KEY, artifact_map, initialize_artifact_tree

__all__ = [
    "ATTENTIONAL_V2_MECHANISM_KEY",
    "ATTENTIONAL_V2_MECHANISM_VERSION",
    "ATTENTIONAL_V2_POLICY_VERSION",
    "ATTENTIONAL_V2_PROMPTS",
    "ATTENTIONAL_V2_PROMPTSET_VERSION",
    "ATTENTIONAL_V2_SCHEMA_VERSION",
    "BRIDGE_RESOLUTION_PROMPT_VERSION",
    "CONTROLLER_DECISION_PROMPT_VERSION",
    "MEANING_UNIT_CLOSURE_PROMPT_VERSION",
    "REACTION_EMISSION_PROMPT_VERSION",
    "ZOOM_READ_PROMPT_VERSION",
    "apply_activation_operations",
    "append_anchor_relation",
    "append_move",
    "append_reconsolidation_record",
    "apply_bridge_state_updates",
    "apply_working_pressure_operations",
    "close_local_meaning_unit",
    "artifact_map",
    "build_default_reader_policy",
    "build_anchor_record",
    "build_book_survey",
    "build_revisit_index",
    "bounded_lookback_source_space",
    "build_empty_anchor_memory",
    "build_empty_local_buffer",
    "build_empty_knowledge_activations",
    "build_empty_move_history",
    "build_empty_reconsolidation_records",
    "build_empty_reflective_summaries",
    "build_empty_trigger_state",
    "build_empty_working_pressure",
    "bridge_resolution",
    "candidate_pool_for_bridge_resolution",
    "controller_decision",
    "derive_anchor_id",
    "flatten_sentence_inventory",
    "generate_candidate_set",
    "initialize_artifact_tree",
    "index_anchor_memory",
    "live_activations",
    "meaning_unit_closure",
    "push_local_buffer_sentence",
    "reaction_emission",
    "refresh_knowledge_modes",
    "replace_policy_section",
    "replace_pressure_bucket",
    "resolve_search_policy_mode",
    "run_phase4_local_cycle",
    "run_phase5_bridge_cycle",
    "set_gate_state",
    "set_knowledge_use_mode",
    "set_pressure_snapshot",
    "set_search_policy_mode",
    "set_trigger_result",
    "upsert_anchor_record",
    "upsert_knowledge_activation",
    "upsert_reflective_item",
    "write_book_survey_artifacts",
    "zoom_read",
]
